# Using Ragas to Evaluate a RAG Application built with LangChain and LangGraph

In the following notebook, we'll be looking at how [Ragas](https://github.com/explodinggradients/ragas) can be helpful in a number of ways when looking to evaluate your RAG applications!

While this example is rooted in LangChain/LangGraph - Ragas is framework agnostic (you don't even need to be using a framework!).

- 🤝 Breakout Room #1
  1. Task 1: Installing Required Libraries
  2. Task 2: Set Environment Variables
  3. Task 3: Synthetic Dataset Generation for Evaluation using Ragas
  4. Task 4: Evaluating our Pipeline with Ragas
  5. Task 6: Making Adjustments and Re-Evaluating

But first! Let's set some dependencies!

## Dependencies and API Keys:

> NOTE: Please skip the pip install commands if you are running the notebook locally.

In [49]:
#!pip install -qU ragas==0.2.10

In [50]:
#!pip install -qU langchain-community==0.3.14 langchain-openai==0.2.14 unstructured==0.16.12 langgraph==0.2.61 langchain-qdrant==0.2.0

We'll also need to provide our API keys.

First, OpenAI's for our LLM/embedding model combination!

In [51]:
import os
from getpass import getpass
os.environ["OPENAI_API_KEY"] = getpass("Please enter your OpenAI API key!")

## Generating Synthetic Test Data

We wil be using Ragas to build out a set of synthetic test questions, references, and reference contexts. This is useful because it will allow us to find out how our system is performing.

> NOTE: Ragas is best suited for finding *directional* changes in your LLM-based systems. The absolute scores aren't comparable in a vacuum.

### Data Preparation

We'll prepare our data - and download our webpages which we'll be using for our data today.

These webpages are from [Simon Willison's](https://simonwillison.net/) yearly "AI learnings".

- [2023 Blog](https://simonwillison.net/2023/Dec/31/ai-in-2023/)
- [2024 Blog](https://simonwillison.net/2024/Dec/31/llms-in-2024/)

Let's start by collecting our data into a useful pile!

In [52]:
!mkdir data

mkdir: data: File exists

In [53]:
!curl https://simonwillison.net/2023/Dec/31/ai-in-2023/ -o data/2023_llms.html

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31524    0 31524    0     0  51916      0 --:--:-- --:--:-- --:--:-- 51934

In [54]:
!curl https://simonwillison.net/2024/Dec/31/llms-in-2024/ -o data/2024_llms.html

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 70549    0 70549    0     0    97k      0 --:--:-- --:--:-- --:--:--   97k-:--:-- --:--:--     0

Next, let's load our data into a familiar LangChain format using the `DirectoryLoader`.

In [55]:
from langchain_community.document_loaders import DirectoryLoader

path = "data/"
loader = DirectoryLoader(path, glob="*.html")
docs = loader.load()

### Knowledge Graph Based Synthetic Generation

Ragas uses a knowledge graph based approach to create data. This is extremely useful as it allows us to create complex queries rather simply. The additional testset complexity allows us to evaluate larger problems more effectively, as systems tend to be very strong on simple evaluation tasks.

Let's start by defining our `generator_llm` (which will generate our questions, summaries, and more), and our `generator_embeddings` which will be useful in building our graph.

### Abstracted SDG

The above method is the full process - but we can shortcut that using the provided abstractions!

This will generate our knowledge graph under the hood, and will - from there - generate our personas and scenarios to construct our queries.

In [56]:
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

In [57]:
from ragas.testset import TestsetGenerator

generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)
dataset = generator.generate_with_langchain_docs(docs, testset_size=10)

Applying HeadlinesExtractor:   0%|          | 0/2 [00:00<?, ?it/s]

Applying HeadlineSplitter:   0%|          | 0/2 [00:00<?, ?it/s]

Applying SummaryExtractor:   0%|          | 0/2 [00:00<?, ?it/s]

Applying CustomNodeFilter:   0%|          | 0/12 [00:00<?, ?it/s]

Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/26 [00:00<?, ?it/s]

Applying [CosineSimilarityBuilder, OverlapScoreBuilder]:   0%|          | 0/2 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/2 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/12 [00:00<?, ?it/s]

In [58]:
dataset.to_pandas()

,user_input,reference_contexts,reference,synthesizer_name
0,"what is Anthropic do with LLMs, they make them...",[We don’t yet know how to build GPT-4 Vibes Ba...,Anthropic is one of the organizations that has...,single_hop_specifc_query_synthesizer
1,Why has GPT-4 not been surpassed by other mode...,[I’m surprised that no-one has beaten the now ...,"According to the context, GPT-4 has not been s...",single_hop_specifc_query_synthesizer
2,What are some key developments related to LLMs...,[Simon Willison’s Weblog Subscribe Stuff we fi...,"In 2023, Large Language Models (LLMs) became a...",single_hop_specifc_query_synthesizer
3,"what openai do in ai world, why people talk ab...",[Microsoft over this issue. The 69 page PDF is...,"openai show up a lot in ai talk, like in tag c...",single_hop_specifc_query_synthesizer
4,How have advancements in large language models...,[<1-hop>\n\nThe rise of inference-scaling “rea...,Advancements in large language models (LLMs) o...,multi_hop_abstract_query_synthesizer
5,How synthetic data in language model training ...,[<1-hop>\n\nThe rise of inference-scaling “rea...,Synthetic data in language model training help...,multi_hop_abstract_query_synthesizer
6,How have advancements in large language models...,[<1-hop>\n\nThe rise of inference-scaling “rea...,Advancements in large language models (LLMs) i...,multi_hop_abstract_query_synthesizer
7,How has the effectiveness of synthetic trainin...,[<1-hop>\n\nThe rise of inference-scaling “rea...,The effectiveness of synthetic training data h...,multi_hop_abstract_query_synthesizer
8,How has Google contributed to the recent advan...,[<1-hop>\n\nWe don’t yet know how to build GPT...,Google has played a significant role in the re...,multi_hop_specific_query_synthesizer
9,What role has Meta played in the adoption of s...,[<1-hop>\n\nmodel available to try out through...,Meta has contributed to the adoption of synthe...,multi_hop_specific_query_synthesizer
10,How does the increasing complexity of large la...,[<1-hop>\n\nof very bad decisions are being ma...,The increasing complexity of large language mo...,multi_hop_specific_query_synthesizer
11,What are the main criticisms of Apple Intellig...,[<1-hop>\n\nSimon Willison’s Weblog Subscribe ...,The main criticisms of Apple Intelligence in 2...,multi_hop_specific_query_synthesizer

## LangChain RAG

Now we'll construct our LangChain RAG, which we will be evaluating using the above created test data!

### R - Retrieval

Let's start with building our retrieval pipeline, which will involve loading the same data we used to create our synthetic test set above.

> NOTE: We need to use the same data - as our test set is specifically designed for this data.

In [59]:
path = "data/"
loader = DirectoryLoader(path, glob="*.html")
docs = loader.load()

Now that we have our data loaded, let's split it into chunks!

In [60]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
split_documents = text_splitter.split_documents(docs)
len(split_documents)

75

#### ❓ Question: 

What is the purpose of the `chunk_overlap` parameter in the `RecursiveCharacterTextSplitter`?

#### 😎 ANSWER #2:

The `chunk_overlap` parameter defines the number of characters that overlap between two adjacent chunks when splitting documents.

The main functions of overlapping are : 
1. **Preserving contextual continuity**: Overlapping prevents concepts, sentences, or paragraphs from being abruptly cut off, which could fragment related information and then impair comprehension.

2. **Reducing information loss at boundaries**: Without overlapping, critical information located at chunk boundaries could be difficult to retrieve because the necessary context would be split between two separate chunks.

3. **Improved retrieval accuracy**: When a query references information that would otherwise be split between two chunks, overlapping increases the likelihood that at least one of the chunks contains sufficient context to be correctly retrieved.

Appropriate overlap represents a balance between chunk granularity (which enables targeted retrieval) and context preservation (which ensures the relevance of answers).

Next up, we'll need to provide an embedding model that we can use to construct our vector store.

In [61]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

Now we can build our in memory QDrant vector store.

In [62]:
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams

client = QdrantClient(":memory:")

client.create_collection(
    collection_name="ai_across_years",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

vector_store = QdrantVectorStore(
    client=client,
    collection_name="ai_across_years",
    embedding=embeddings,
)

We can now add our documents to our vector store.

In [63]:
_ = vector_store.add_documents(documents=split_documents)

Let's define our retriever.

In [64]:
retriever = vector_store.as_retriever(search_kwargs={"k": 5})

Now we can produce a node for retrieval!

In [65]:
def retrieve(state):
  retrieved_docs = retriever.invoke(state["question"])
  return {"context" : retrieved_docs}

### Augmented

Let's create a simple RAG prompt!

In [66]:
from langchain.prompts import ChatPromptTemplate

RAG_PROMPT = """\
You are a helpful assistant who answers questions based on provided context. You must only use the provided context, and cannot use your own knowledge.

### Question
{question}

### Context
{context}
"""

rag_prompt = ChatPromptTemplate.from_template(RAG_PROMPT)

### Generation

We'll also need an LLM to generate responses - we'll use `gpt-4o-mini` to avoid using the same model as our judge model.

In [67]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4o-mini")

Then we can create a `generate` node!

In [68]:
def generate(state):
  docs_content = "\n\n".join(doc.page_content for doc in state["context"])
  messages = rag_prompt.format_messages(question=state["question"], context=docs_content)
  response = llm.invoke(messages)
  return {"response" : response.content}

### Building RAG Graph with LangGraph

Let's create some state for our LangGraph RAG graph!

In [69]:
from langgraph.graph import START, StateGraph
from typing_extensions import List, TypedDict
from langchain_core.documents import Document

class State(TypedDict):
  question: str
  context: List[Document]
  response: str

Now we can build our simple graph!

> NOTE: We're using `add_sequence` since we will always move from retrieval to generation. This is essentially building a chain in LangGraph.

In [70]:
graph_builder = StateGraph(State).add_sequence([retrieve, generate])
graph_builder.add_edge(START, "retrieve")
graph = graph_builder.compile()

Let's do a test to make sure it's doing what we'd expect.

In [71]:
response = graph.invoke({"question" : "How are LLM agents useful?"})

In [72]:
response["response"]

"LLM agents can be useful in various contexts, primarily as digital assistants that can perform tasks on behalf of users, akin to a travel agent model. They can also be employed to solve problems by utilizing tools and running processes in a loop, enhancing their effectiveness.\n\nHowever, there is skepticism regarding their utility due to challenges like gullibility, as LLMs can struggle to distinguish between truth and fiction. This raises concerns about their reliability and the quality of decisions they make on users' behalf. Some view them as potentially more harmful than beneficial, while others believe they could pose an existential threat.\n\nDespite these concerns, LLMs are relatively easy to build, requiring only a few hundred lines of code, provided there is ample quality training data. The increasing accessibility of running LLMs on personal devices has also contributed to their growing presence and potential utility.\n\nLLMs warrant criticism for various reasons, including environmental impact and ethical concerns, but they can also be remarkably effective in certain applications, such as code generation. Their ability to run and test code generated can mitigate issues like hallucination, which is a significant challenge in other areas. Overall, while skepticism exists, LLMs demonstrate considerable potential for usefulness in specific scenarios."

## Evaluating the App with Ragas

Now we can finally do our evaluation!

We'll start by running the queries we generated usign SDG above through our application to get context and responses.

In [73]:
for test_row in dataset:
  response = graph.invoke({"question" : test_row.eval_sample.user_input})
  test_row.eval_sample.response = response["response"]
  test_row.eval_sample.retrieved_contexts = [context.page_content for context in response["context"]]

In [74]:
dataset.to_pandas()

,user_input,retrieved_contexts,reference_contexts,response,reference,synthesizer_name
0,"what is Anthropic do with LLMs, they make them...","[If you can gather the right data, and afford ...",[We don’t yet know how to build GPT-4 Vibes Ba...,"Anthropic produces LLMs, as they are mentioned...",Anthropic is one of the organizations that has...,single_hop_specifc_query_synthesizer
1,Why has GPT-4 not been surpassed by other mode...,[This is a huge advantage for open over closed...,[I’m surprised that no-one has beaten the now ...,GPT-4 has not been surpassed by other models y...,"According to the context, GPT-4 has not been s...",single_hop_specifc_query_synthesizer
2,What are some key developments related to LLMs...,[This is Things we learned about LLMs in 2024 ...,[Simon Willison’s Weblog Subscribe Stuff we fi...,Some key developments related to LLMs in 2023 ...,"In 2023, Large Language Models (LLMs) became a...",single_hop_specifc_query_synthesizer
3,"what openai do in ai world, why people talk ab...","[That era appears to have ended, likely perman...",[Microsoft over this issue. The 69 page PDF is...,OpenAI has made significant contributions to t...,"openai show up a lot in ai talk, like in tag c...",single_hop_specifc_query_synthesizer
4,How have advancements in large language models...,[In October I upgraded my LLM CLI tool to supp...,[<1-hop>\n\nThe rise of inference-scaling “rea...,"Advancements in large language models (LLMs), ...",Advancements in large language models (LLMs) o...,multi_hop_abstract_query_synthesizer
5,How synthetic data in language model training ...,[One of the best descriptions I’ve seen of thi...,[<1-hop>\n\nThe rise of inference-scaling “rea...,Synthetic data in language model training help...,Synthetic data in language model training help...,multi_hop_abstract_query_synthesizer
6,How have advancements in large language models...,[In October I upgraded my LLM CLI tool to supp...,[<1-hop>\n\nThe rise of inference-scaling “rea...,Advancements in large language models (LLMs) i...,Advancements in large language models (LLMs) i...,multi_hop_abstract_query_synthesizer
7,How has the effectiveness of synthetic trainin...,[One of the best descriptions I’ve seen of thi...,[<1-hop>\n\nThe rise of inference-scaling “rea...,The effectiveness of synthetic training data h...,The effectiveness of synthetic training data h...,multi_hop_abstract_query_synthesizer
8,How has Google contributed to the recent advan...,[I wrote about this at the time in The killer ...,[<1-hop>\n\nWe don’t yet know how to build GPT...,Google has made significant contributions to a...,Google has played a significant role in the re...,multi_hop_specific_query_synthesizer
9,What role has Meta played in the adoption of s...,[One of the best descriptions I’ve seen of thi...,[<1-hop>\n\nmodel available to try out through...,Meta has played a significant role in the adop...,Meta has contributed to the adoption of synthe...,multi_hop_specific_query_synthesizer
10,How does the increasing complexity of large la...,[Did you know ChatGPT has two entirely differe...,[<1-hop>\n\nof very bad decisions are being ma...,The increasing complexity of large language mo...,The increasing complexity of large language mo...,multi_hop_specific_query_synthesizer
11,What are the main criticisms of Apple Intellig...,"[Apple Intelligence is bad, Apple’s MLX librar...",[<1-hop>\n\nSimon Willison’s Weblog Subscribe ...,The main criticisms of Apple Intelligence in 2...,The main criticisms of Apple Intelligence in 2...,multi_hop_specific_query_synthesizer

Then we can convert that table into a `EvaluationDataset` which will make the process of evaluation smoother.

In [75]:
from ragas import EvaluationDataset

evaluation_dataset = EvaluationDataset.from_pandas(dataset.to_pandas())

We'll need to select a judge model - in this case we're using the same model that was used to generate our Synthetic Data.

In [76]:
# from ragas import evaluate
from ragas.llms import LangchainLLMWrapper

evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o"))

Next up - we simply evaluate on our desired metrics!

In [77]:
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy, ContextEntityRecall, NoiseSensitivity
from ragas import evaluate, RunConfig

#custom_run_config = RunConfig(timeout=360)

# I made this change because I got to many rate limit errors
custom_run_config = RunConfig(
    timeout=600, 
    max_workers=2  # 2 jobs at a time to avoid rate limiting
)

result = evaluate(
    dataset=evaluation_dataset,
    metrics=[LLMContextRecall(), Faithfulness(), FactualCorrectness(), ResponseRelevancy(), ContextEntityRecall(), NoiseSensitivity()],
    llm=evaluator_llm,
    run_config=custom_run_config
)
result

Evaluating:   0%|          | 0/72 [00:00<?, ?it/s]

{'context_recall': 0.5512, 'faithfulness': 0.7582, 'factual_correctness': 0.5767, 'answer_relevancy': 0.9460, 'context_entity_recall': 0.4511, 'noise_sensitivity_relevant': 0.2441}

## Making Adjustments and Re-Evaluating

Now that we've got our baseline - let's make a change and see how the model improves or doesn't improve!

> NOTE: This will be using Cohere's Rerank model (which was updated fairly [recently](https://docs.cohere.com/v2/changelog/rerank-v3.5)) - please be sure to [sign-up for an API key!](https://docs.cohere.com/reference/about)

In [78]:
os.environ["COHERE_API_KEY"] = getpass("Please enter your Cohere API key!")

In [79]:
#!pip install -qU cohere langchain_cohere


We'll first set our retriever to return more documents, which will allow us to take advantage of the reranking.

In [80]:
retriever = vector_store.as_retriever(search_kwargs={"k": 20})

Reranking, or contextual compression, is a technique that uses a reranker to compress the retrieved documents into a smaller set of documents.

This is essentially a slower, more accurate form of semantic similarity that we use on a smaller subset of our documents.

In [81]:
from langchain.retrievers.contextual_compression import ContextualCompressionRetriever
from langchain_cohere import CohereRerank

def retrieve_adjusted(state):
  compressor = CohereRerank(model="rerank-v3.5")
  compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever, search_kwargs={"k": 5}
  )
  retrieved_docs = compression_retriever.invoke(state["question"])
  return {"context" : retrieved_docs}

We can simply rebuild our graph with the new retriever!

In [82]:
class State(TypedDict):
  question: str
  context: List[Document]
  response: str

graph_builder = StateGraph(State).add_sequence([retrieve_adjusted, generate])
graph_builder.add_edge(START, "retrieve_adjusted")
graph = graph_builder.compile()

In [83]:
response = graph.invoke({"question" : "How are LLM agents useful?"})
response["response"]

'LLM agents are seen as potentially useful in two main ways. First, they can act on behalf of users, similar to a travel agent, by making decisions or taking actions based on user inputs. This perspective suggests that they could automate tasks and solve problems independently. However, there is skepticism regarding their effectiveness due to their inherent gullibility; LLMs may struggle to distinguish truth from fiction, which poses challenges in making meaningful decisions.\n\nSecond, LLMs have shown particular strength in writing code. The structure and grammar of programming languages are less complex than natural languages, which allows LLMs to excel in this area. This capability is noted as one of the most promising applications of LLMs.\n\nDespite these potential uses, there is a prevailing concern about the reliability and ethical implications of LLM agents, leading to criticism and skepticism about their overall utility in practice.'

In [84]:
import time

for test_row in dataset:
  response = graph.invoke({"question" : test_row.eval_sample.user_input})
  test_row.eval_sample.response = response["response"]
  test_row.eval_sample.retrieved_contexts = [context.page_content for context in response["context"]]
  time.sleep(2) # To try to avoid rate limiting.

In [85]:
# rerun the previous cell to get the updated dataset
evaluation_dataset = EvaluationDataset.from_pandas(dataset.to_pandas())

In [86]:
result = evaluate(
    dataset=evaluation_dataset,
    metrics=[LLMContextRecall(), Faithfulness(), FactualCorrectness(), ResponseRelevancy(), ContextEntityRecall(), NoiseSensitivity()],
    llm=evaluator_llm,
    run_config=custom_run_config
)
result

Evaluating:   0%|          | 0/72 [00:00<?, ?it/s]

{'context_recall': 0.6720, 'faithfulness': 0.7225, 'factual_correctness': 0.5800, 'answer_relevancy': 0.9400, 'context_entity_recall': 0.4280, 'noise_sensitivity_relevant': 0.2914}

#### ❓ Question: 

Which system performed better, on what metrics, and why?